### ISSUE TITLE
Missing overload for `PlatformGetEnvironmentVar`

### ISSUE THREAD

**Issue by japantreepot** [scallyw4g/bonsai_stdlib#2]
`PlatformGetEnvironmentVar(const char *VarName, memory_arena *Memory)` is only defined for win32 platforms, not for unix platforms, causing the `poof` build to fail.

https://github.com/scallyw4g/poof/blob/def576952381dc49b5d42292a30d3fb73a6fde96/poof/poof.cpp#L5845
calls the two argument function, but only the one argument function is defined.

**Comment by scallyw4g** [comment]
Thanks for opening this.  This is one of those bonehead things I introduced because there's no CI/CD for Bonsai/poof.  I'll be fixing that the next time I get some time to work on these projects.

**Comment by japantreepot** [comment]
Looking at the man page for `getenv`, I do not think we can implement this in a way that makes sense. 

`getenv` returns a pointer to a string whose storage is managed by something else, not us, so it does not makes sense for us to allocate it in our arena.

The only reason we might use our arena is if we copy it for later modification, since the pointer given to us by `getenv` is read-only.

So should we just not bother with the arena for that one call? What do you think?

**Comment by scallyw4g** [comment]
The Windows one calls a Win32 API that returns a copy of the string, so the linux one should probably do the same.

There are functions in `counted_string.cpp` called CopyString that you should be able to use to copy a string.  There are also 'constructors' for counted strings called `CS` that you can pass a `const char*` to that makes a `counted_string`.

I can fix this when I'm home on Sunday, or feel free to take a crack at it yourself 😄
